
# this voxceleb1 is doing speaker classification task!
runner:
  total_steps: 200000
  gradient_clipping: 1
  gradient_accumulate_steps: 1

  log_step: 500
  eval_step: 5000
  save_step: 1000
  max_keep: 1
  eval_dataloaders: 
    - dev
    - test
  
optimizer:
  name: TorchOptim
  torch_optim_name: Adam
  lr: 1.0e-4

# # comment the whole scheduler config block to disable learning rate scheduling
scheduler:
   name: linear_schedule_with_warmup
   num_warmup_steps: 500

downstream_expert: 
  datarc:
    file_path: D:/datasets/voxceleb1
    meta_data: ./downstream/voxceleb1/veri_test_class.txt
    num_workers: 4
    train_batch_size: 2
    eval_batch_size: 1
    max_timestep: 64000

  modelrc:
    projector_dim: 256
    select: UtteranceLevel
    UtteranceLevel:
      pooling: MeanPooling
